title: Shibaji Chakraborty
logo: /assests/img/headshot_circle.png
description: Postdoctoral Associate
theme: jekyll-theme-minimal

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-default-layout
